### PR TITLE
Update download-maven-plugin from 1.6.8 to 1.7.0

### PR DESCRIPTION
**Pull request by phillip-kruger**

### CODE REVIEW

**Comment by phillip-kruger** [comment]
@xstefank not sure why, but build pass for me ??

**Comment by xstefank** [comment]
locally, it's still failing for me even with this branch. I think this will be something wrong with unpkg.com.

**Comment by xstefank** [comment]
This PR is passing because the files are already available and not being downloaded.

[INFO] --- download-maven-plugin:1.7.0:wget (install-bootstrap-css) @ smallrye-health-ui ---
[INFO] File already exist, skipping

**Comment by xstefank** [comment]
@phillip-kruger will rework these downloads with a more suitable solution. Closing this in favor of this new solution.

**Pull request closed without merging**
