### PR TITLE
Update to MP Health 2.0-RC1

### LINKED ISSUE #30: Rename outcome to status
To follow changes done in /eclipse/microprofile-health/issues/125

### LINKED ISSUE #34: Update to MP Health 2.0-RC1
Update to microprofile-health:2.0-RC1 covering mainly addition of liveness and readiness

### PR DESCRIPTION
**Pull request by xstefank**
* Renaming of `outcome` and `state` JSON fields to `status`
* Add liveness and readiness checks

resolves #30 
resolves #34

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Should there be an update to the MP Health version as well?

If there's an RC we should be able to link to it

**Comment by xstefank** [comment]
@kenfinnigan there is an update in this PR. Should that go into separate PR? I am not sure if we even do RC updates in smallrye projects but I want to do some additional work on the spec before GA so I needed the updated implementation.

**Comment by kenfinnigan** [comment]
Is there a new MP spec JAR available? I would expect to see the version of the spec being updated to support RC.

Normally SmallRye projects wouldn't sit on an RC release, but for a short time before the full release is available to facilitate collaboration is fine

**Comment by xstefank** [comment]
[spec API jar](https://mvnrepository.com/artifact/org.eclipse.microprofile.health/microprofile-health-api/2.0-RC1)
[spec TCK jar](https://mvnrepository.com/artifact/org.eclipse.microprofile.health/microprofile-health-tck/2.0-RC1)

and the spec update in this PR - https://github.com/smallrye/smallrye-health/pull/35/files#diff-600376dffeb79835ede4a0b285078036R37

Am I missing something?

**Comment by kenfinnigan** [comment]
Sorry, not quite sure how I kept missing that change!

**Pull request merged**
