### PR TITLE
Make the use of servlet optional

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by sberyozkin** [comment]
Making the servlet optional will let those users who do not want to use servlet reuse the common code instead; I'd still like to keep a servlet there spo that something is available OOB, should be ok given that the servlet api is provided

**Comment by kenfinnigan** [comment]
Servlet technically isn't provided though. There's no spec dependency on Servlet from JAX-RS, so it is possible that a JAX-RS container isn't built on Servlets

**Comment by sberyozkin** [comment]
HttpServletRequest/Response as well as ServletContext/Config are supported injectable contexts in JAX-RS; though may be I'm missing the point :-). I can remove this servlet altogether now or later, I just thought about starting to separate the servlet from the actual Health collection code

**Comment by sberyozkin** [comment]
One thing which is I'm finding useful in keeping the servlet inside small rye health is that without it the implementation will be incomplete, even though I did push most of Health accumulation code into a standalone bean, setting 503 status on the http response in case of DOWN is still needed. So at least in those cases where the 3rd party containers can rely on Servlet it just works OOB. 
Only in cases where for example we have Undertow handlers or JAX-RS one would still need to set 503 manually, while reusing SmallRyeHealthReporter bean, the fact the small rye health code ships SmallRyeHealthReporter won't affect for example Undertow integration where no Servlet API is supported because this API is optional at the pom level

**Comment by kenfinnigan** [comment]
For this situation I almost think the servlet should be added to the TCK to facilitate passing it, and that's it.

Currently the servlet spec is "provided" which means it's lack of presence in a runtime situation would cause a failure to start because of a ClassNotFoundException.

It's for that reason I think the use of servlet needs to be removed. At least for now. In the future we could look to adding some kind of SPI maybe for offering that behavior that can then be implemented by a runtime however they want

**Comment by sberyozkin** [comment]
It just works with the servlet with Thorntail v2 and v4 so I'm not sure when it would not work, and when the users would want to depend on servlet and it won't work the users will just add the servlet api to their poms. Or are you saying that even if the users do not use this Servlet some containers will still try to load it ?

I'm not sure about SPIs either. If the users do not like the way small rye builds the health response then may be they will be better of just building their own library or do a custom health handler given that the only real work the small rye does is it builds the standard MP Health response ?

The only thing which varies now, with moving most of the code to a non-servlet aware bean is the way 503 is set as it is indeed specific to servlets, JAX-RS or Undertow.

I guess I will go ahead then and remove the servlet, but that would mean the implementation will immediately become incomplete. Should we still keep the servlet, at least for now :-), and remove it immediately when someone sees a problem ? Or you'd really prefer to get it removed now ?
thanks

**Comment by bobmcwhirter** [comment]
I think the WildFly folks want to use direct Undertow handlers, below the Servlet level.

**Comment by kenfinnigan** [comment]
I think it's fine to be "incomplete", as I don't expect most SmallRye impls to work without some level of integration.

In some cases that means adding the necessary integration into testing the TCK to make sure it passes.

And then likely documenting what integration is required to make it work

**Comment by sberyozkin** [comment]
Hi Bob, yes, I believe this is what I did, see
https://github.com/sberyozkin/smallrye-health/blob/1b83863dfdc7045ce408e02295f16673b6b2436c/implementation/src/main/java/io/smallrye/health/SmallRyeHealthServlet.java
so the servlet is there but my understanding it won't interfere with Undertow handlers where to use only the bean the way this servlet does.

Hi Ken, ok, I'll just move this servlet to the TCK

thanks

**Comment by sberyozkin** [comment]
I've removed the servlet

**Comment by jmesnil** [comment]
@sberyozkin thanks for looking at this!

**Pull request merged**
